#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done
for appdir in /srv/shiny-server/* ; do
	if [ -f "$appdir"/install_deps.sh ] ; then
		"$appdir"/install_deps.sh
	fi
done
exit 0
